web:
    restart: always
    build: ./web
    expose:
        - "8080"
    ports:
        - "8080:8080"
    volumes:
        - /usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn -w 4 --bind :8080 app:app

proxy:
    restart: always
    build: ./proxy
    expose:
        - "80"
    ports:
        - "80:80"
    volumes_from:
        - web
    links:
        - web:web

redis:
    image: redis
